stages:
  - prepare
  - build
  - test
  - docker
  - stg
  - prod

include:
  - project: "cicd-blueprints/pipeline-modules/ci/nodejs"
    file: "main.gitlab-ci.yml"
    ref: 11.0.2
  - project: "cicd-blueprints/pipeline-modules/cd/flux"
    file: "main.gitlab-ci.yml"
    ref: 3.4.0
  - project: "cicd-blueprints/pipelines/multi-branch-deployment"
    file: "main.gitlab-ci.yml"
    ref: 1.3.3

# Adjust only "PROVIDER_IMAGE_TAG" to your needs. This will set the tag of the docker image to be deployed. This docker image tag cannot be updated once the branch is deployed!
variables:
  STG_DEPLOY_BRANCH: "master"
  SETTINGS_IMAGE_TAG: $CI_COMMIT_BRANCH
  DEPLOYMENT_REPO: git@gitlab.id-repository.de:west/deployments.git
  DEPLOYMENT: settings-ui
  DEPLOY_BRANCH_STG: "false" # "branch deployment that is overwriting branch is not required"
  REPO: ippendigital
  IMAGE_NAME: settings-ui
  FLUX_FORWARD_NAMESPACE: west
  NODE_VERSION: 19
  CYPRESS_VERSION: node16.5.0-chrome94-ff93
  NPM_INSTALL: "true"
  CSS_LINT: "false"
  ES_LINT: "true"
  BUILD: "false"
  AUDIT: "false"
  UNIT_TEST: "false"
  INTEGRATION_TEST: "false"
  AUTO_DEPLOY_PROD: "false"

# from nodejs
docker:
  extends: .build-and-push-docker
