export const BlackListClients = [
    "24vest.de",
    "Anzeigenzeitungsverlag",
    "Blickpunkt Nienburg",
    "Christkindlmarkt Rosenheim",
    "DA-imNetz.de",
    "Dachauer Rundschau",
    "Frankfurter Wochenblatt",
    "freising-online",
    "fussball-vorort.de",
    "Hersfelder Zeitung",
    "HNA 7",
    "Hytiva News",
    "id-regioportal",
    "LocalXXL",
    "lust-tz",
    "Mailing Marketing",
    "Merkur CUP",
    "merkur-online",
    "msl24",
    "Mühldorfer Volksfest",
    "München Meta",
    "mydocumenta",
    "niederbayern24.de",
    "nordbuzz",
    "owl24",
    "REGIONAL.report",
    "Selenium Testclient",
    "Setup Template",
    "SiegerlandKurier",
    "Solinger Tageblatt",
    "Streiflichter",
    "trainingsworld.com",
    "weser-kurier",
    "WOPO24",
    "Zentralredaktion",
];
